name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ollama-ui:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/ollama-ui:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up oc CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xzf oc.tar.gz
        sudo mv oc /usr/local/bin/

    - name: Log in to OpenShift
      run: oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }}

    - name: Deploy to OpenShift
      run: |
        oc project ${{ secrets.OPENSHIFT_PROJECT }}
        oc import-image ollama-ui:latest --from=docker.io/${{ secrets.DOCKER_USERNAME }}/ollama-ui:latest --confirm
        oc rollout latest dc/ollama-ui
